### ISSUE TITLE
Finance Clerk approval routing fix extraneous steps

### ISSUE THREAD

**Issue by techmastermike** [KPB-US/budgy#43]
Right now if Penny creates, it goes to Craig for approval, then back to her for approval, then back to Craig or Brandi, then back to her for posting. Blurgh.

**Comment by mfrederickson** [comment]
It is following the flow. What's extraneous about it-- how should it flow instead? I think for certain scenarios there is no getting around it... 

If we flag allow the routing steps for her as approved when she approves the first of hers, how do we know that she didn't actually need something from a prior approval step from someone else before approving her latter routing step?  

Remember, it's anyone in the finance-clerk role that can post, not just her.  I don't think we can get around this because some clerk must post after all is said and done.

I'm not sure how we should proceed on this...

**Comment by techmastermike** [comment]
I concur. If they create/save/approve their own record - that's just a bonus feature of working in Finance. The net time saved using this app should supersede any inconveniences of an extra email occasionally.
